togo

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -43,6 +43,17 @@ jobs:
       run: |
         choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --quiet --includeRecommended"
         choco install cmake --version=3.25.1 --installargs 'ADD_CMAKE_TO_PATH=System'
+        if not exist "C:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Auxiliary/Build/vcvarsall.bat" (
+          echo "Error: vcvarsall.bat not found!" && exit 1
+        )
+    - name: Verify vcvarsall.bat presence
+      if: matrix.os == 'windows-latest'
+      run: |
+        if exist "C:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Auxiliary/Build/vcvarsall.bat" (
+          echo "vcvarsall.bat found."
+        ) else (
+          echo "Error: vcvarsall.bat not found!" && exit 1
+        )
 
     - name: Configure CMake with CPM on Windows
       if: matrix.os == 'windows-latest'
